"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { useState } from "react";
import { RecoilRoot } from "recoil";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [isDark, setIsDark] = useState(true);
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          backgroundColor: isDark ? "black" : "white",
          color: isDark ? "white" : "black",
          transition: "all .5s ease",
        }}
      >
        <RecoilRoot>
          <button onClick={() => setIsDark((c) => !c)}>
            {isDark ? "Light" : "Dark"}
          </button>
          <main className="container">
            <Navbar />
            {children}
            <Footer />
          </main>
        </RecoilRoot>
      </body>
    </html>
  );
}
